version: "3.2"
services:
  nginx:
    restart: on-failure
    image: nginx:1.19.7-alpine
    volumes:
       - ./flask.conf:/etc/nginx/conf.d/default.conf
       - /tmp/log/nginx/flask/access.log:/var/log/nginx/flask/access.log
    ports:
      - 80:80
  nginx-exporter:
    restart: on-failure
    image: quay.io/martinhelmich/prometheus-nginxlog-exporter
    command: ["/var/log/nginx/flask/access.log"]
    volumes:
       - ./nginx_exporter.hcl:/etc/prometheus-nginxlog-exporter.hcl
       - /tmp/log/nginx/flask/access.log:/var/log/nginx/flask/access.log:ro
    ports:
      - 4040:4040
  flask:
    restart: on-failure
    image: nubacuk/devops-flask-test
    ports:
      - 127.0.0.1:5000:5000
  prometheus:
    restart: on-failure
    image: prom/prometheus:v2.25.0
    volumes:
       - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
  grafana:
    restart: on-failure
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    image: grafana/grafana:7.4.3-ubuntu
    ports:
      - 3000:3000
  bench:
    image: jordi/ab
    command: ["-n 1000", "-c 100", "http://nginx/"]